// Hàm hỗ trợ
const getFallbackImage = (title) => {
    const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="600" height="400" viewBox="0 0 600 400"><rect width="100%" height="100%" fill="#171717"/><text x="50%" y="50%" dominant-baseline="middle" text-anchor="middle" font-family="sans-serif" font-size="24" font-weight="bold" fill="#f43f5e">${title}</text></svg>`;
    return `data:image/svg+xml;charset=utf-8,${encodeURIComponent(svg)}`;
};

const formatMoney = (amount) => new Intl.NumberFormat('vi-VN', { style: 'currency', currency: 'VND' }).format(amount);
const generateGoogleMapsLink = (loc) => `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(loc + ' TP.HCM')}`;

// Dữ liệu 35 Combo
const combos = [
    { id: 1, title: "Acoustic Chill", desc: "Nghe nhạc Acoustic & Dạo phố đi bộ", address: "Phố đi bộ Nguyễn Huệ, Quận 1", district: "quan1", partner: "Oromia Coffee", discount: "15%", price: 150000, partnerTier: "basic", estimatedAOV: 150000, commissionRate: 0.05, baseFee: 8000, visibilityLevel: "normal", category: "low", target: "couple", bookings: 125, img: "https://images.unsplash.com/photo-1510915358317-1ce47b5d42ea?auto=format&fit=crop&w=800&q=80", icon: "fa-guitar", itinerary: [{time:"19:00",activity:"Nghe nhạc Sống",location:"Oromia Coffee"},{time:"21:00",activity:"Dạo mát",location:"Phố đi bộ"},{time:"22:00",activity:"Ăn vặt",location:"Chung cư 42"}] },
    { id: 2, title: "Phim Đêm & Vỉa Hè", desc: "Xem phim rạp & Ăn vặt bánh tráng", address: "CGV Sư Vạn Hạnh, Quận 10", district: "quan10", partner: "CGV Cinemas", discount: "20%", price: 250000, partnerTier: "premium", estimatedAOV: 250000, commissionRate: 0.09, baseFee: 18000, visibilityLevel: "featured", category: "mid", target: "both", bookings: 89, img: "https://images.unsplash.com/photo-1536440136628-849c177e76a1?auto=format&fit=crop&w=800&q=80", icon: "fa-film", itinerary: [{time:"20:00",activity:"Xem phim bom tấn",location:"CGV Vạn Hạnh Mall"},{time:"22:30",activity:"Ăn bánh tráng nướng",location:"Hồ Thị Kỷ"}] },
    { id: 3, title: "Đấu Trí Boardgame", desc: "Chơi Boardgame & Uống trà sữa", address: "Cashflow Cafe, Quận 10", district: "quan10", partner: "Cashflow Boardgame", discount: "10%", price: 150000, partnerTier: "basic", estimatedAOV: 150000, commissionRate: 0.05, baseFee: 8000, visibilityLevel: "normal", category: "low", target: "group", bookings: 142, img: "https://images.unsplash.com/photo-1518544801976-4df45e0f5d72?auto=format&fit=crop&w=800&q=80", icon: "fa-chess-knight", itinerary: [{time:"18:30",activity:"Ăn tối",location:"Mì Ý Double B"},{time:"19:30",activity:"Ma Sói, Uno...",location:"Cashflow Cafe"}] },
    { id: 4, title: "Tầng Mây Landmark", desc: "Trượt băng & Ăn lẩu Haidilao", address: "Landmark 81, Bình Thạnh", district: "binhthanh", partner: "Haidilao Hotpot", discount: "50K", price: 800000, partnerTier: "premium", estimatedAOV: 800000, commissionRate: 0.09, baseFee: 18000, visibilityLevel: "featured", category: "high", target: "couple", bookings: 315, img: "https://images.unsplash.com/photo-1596525164057-2e11894a4b41?auto=format&fit=crop&w=800&q=80", icon: "fa-building", itinerary: [{time:"17:00",activity:"Trượt băng",location:"Vincom Ice Rink"},{time:"19:30",activity:"Ăn lẩu múa mì",location:"Haidilao Tầng 3"}] },
    { id: 5, title: "Picnic Sống Ảo", desc: "Dã ngoại Thảo Cầm Viên", address: "Thảo Cầm Viên, Quận 1", district: "quan1", partner: "Phúc Long Coffee", discount: "15%", price: 120000, partnerTier: "basic", estimatedAOV: 120000, commissionRate: 0.05, baseFee: 8000, visibilityLevel: "mood", category: "low", target: "group", bookings: 67, img: "https://images.unsplash.com/photo-1587334274328-64186a80aeb9?auto=format&fit=crop&w=800&q=80", icon: "fa-tree", itinerary: [{time:"08:30",activity:"Mua cafe",location:"Phúc Long Lê Duẩn"},{time:"09:00",activity:"Trải thảm Picnic",location:"Thảo Cầm Viên"},{time:"11:30",activity:"Ăn trưa",location:"Dưới bóng cây"}] },
    { id: 6, title: "Hoàng Hôn SUP", desc: "Chèo SUP & Tiệc nướng BBQ", address: "Bến SUP Thanh Đa, Bình Thạnh", district: "binhthanh", partner: "Saigon SUP Club", discount: "20%", price: 750000, partnerTier: "premium", estimatedAOV: 750000, commissionRate: 0.09, baseFee: 18000, visibilityLevel: "featured", category: "high", target: "group", bookings: 278, img: "https://images.unsplash.com/photo-1532454044158-b6487e4dd33a?auto=format&fit=crop&w=800&q=80", icon: "fa-water", itinerary: [{time:"16:00",activity:"Nhận SUP",location:"Saigon SUP Club"},{time:"16:30",activity:"Chèo SUP ngắm hoàng hôn",location:"Bán đảo Thanh Đa"},{time:"18:30",activity:"Tiệc nướng BBQ",location:"Khu vực BBQ"}] },
    { id: 7, title: "Làm Gốm Nghệ Thuật", desc: "Workshop làm gốm đôi & Cafe", address: "Haru Craft Studio, Quận 1", district: "quan1", partner: "Haru Craft", discount: "10%", price: 450000, partnerTier: "premium", estimatedAOV: 450000, commissionRate: 0.09, baseFee: 18000, visibilityLevel: "mood", category: "high", target: "couple", bookings: 134, img: "https://images.unsplash.com/photo-1610701596007-11502861dcfa?auto=format&fit=crop&w=800&q=80", icon: "fa-hands", itinerary: [{time:"14:00",activity:"Làm gốm",location:"Haru Craft Studio"},{time:"17:00",activity:"Uống nước, tâm sự",location:"Mockingbird Cafe"}] },
    { id: 8, title: "Bảo Tàng Cổ Điển", desc: "Bảo tàng Mỹ thuật & Chụp ảnh Retro", address: "Bảo tàng Mỹ thuật, Quận 1", district: "quan1", partner: "Cơm Tấm Mộc", discount: "15%", price: 100000, partnerTier: "basic", estimatedAOV: 100000, commissionRate: 0.05, baseFee: 8000, visibilityLevel: "normal", category: "low", target: "both", bookings: 112, img: "https://images.unsplash.com/photo-1582555172866-f73bb12a2ab3?auto=format&fit=crop&w=800&q=80", icon: "fa-palette", itinerary: [{time:"09:00",activity:"Tham quan kiến trúc",location:"Bảo tàng Mỹ thuật"},{time:"11:30",activity:"Ăn trưa cơm tấm",location:"Cơm tấm Mộc"}] },
    { id: 9, title: "Gió Sông Sài Gòn", desc: "Waterbus ngắm hoàng hôn & Ăn tối", address: "Bến Bạch Đằng, Quận 1", district: "quan1", partner: "Saigon Waterbus", discount: "10%", price: 300000, partnerTier: "growth", estimatedAOV: 300000, commissionRate: 0.07, baseFee: 12000, visibilityLevel: "featured", category: "mid", target: "both", bookings: 189, img: "https://images.unsplash.com/photo-1598813354460-70fbf1c02ab4?auto=format&fit=crop&w=800&q=80", icon: "fa-ship", itinerary: [{time:"16:30",activity:"Lên tàu Waterbus",location:"Bến Bạch Đằng"},{time:"18:30",activity:"Ăn tối ven sông",location:"Khu ẩm thực Bến Bạch Đằng"}] },
    { id: 10, title: "Workshop Nặn Tượng", desc: "Tô tượng, nặn đất sét xả stress", address: "Họa Sĩ Cà Phê, Bình Thạnh", district: "binhthanh", partner: "Họa Sĩ Cà Phê", discount: "20%", price: 180000, partnerTier: "premium", estimatedAOV: 180000, commissionRate: 0.09, baseFee: 18000, visibilityLevel: "mood", category: "low", target: "group", bookings: 145, img: "https://images.unsplash.com/photo-1460661419201-64f96e0eb9da?auto=format&fit=crop&w=800&q=80", icon: "fa-face-smile", itinerary: [{time:"15:00",activity:"Tô tượng/đất sét",location:"Họa Sĩ Cà Phê"},{time:"18:00",activity:"Ăn Bún bò Huế",location:"Ngã tư Hàng Xanh"}] },
    { id: 11, title: "Thiện Xạ Bắn Cung", desc: "Câu lạc bộ Bắn cung & Ăn Gà rán", address: "NVH Thanh Niên, Quận 1", district: "quan1", partner: "Don Chicken", discount: "15%", price: 350000, partnerTier: "growth", estimatedAOV: 350000, commissionRate: 0.07, baseFee: 12000, visibilityLevel: "normal", category: "mid", target: "group", bookings: 167, img: "https://images.unsplash.com/photo-1511250275811-9a74b0ed69bd?auto=format&fit=crop&w=800&q=80", icon: "fa-bullseye", itinerary: [{time:"17:00",activity:"Bắn cung",location:"NVH Thanh Niên"},{time:"19:30",activity:"Phạt người thua",location:"Don Chicken"}] },
    { id: 12, title: "Nightlife Chill", desc: "Pub Acoustic nhẹ nhàng & Cocktails", address: "Carmen Bar, Quận 1", district: "quan1", partner: "Carmen Bar", discount: "10%", price: 550000, partnerTier: "premium", estimatedAOV: 550000, commissionRate: 0.09, baseFee: 18000, visibilityLevel: "featured", category: "high", target: "couple", bookings: 210, img: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?auto=format&fit=crop&w=800&q=80", icon: "fa-martini-glass", itinerary: [{time:"19:30",activity:"Ăn tối món Âu",location:"El Gaucho"},{time:"21:00",activity:"Cocktail & Nghe nhạc",location:"Carmen Bar"}] },
    { id: 13, title: "Càn Quét Hồ Thị Kỷ", desc: "Ăn sập Phố Hồ Thị Kỷ", address: "Phố ẩm thực Hồ Thị Kỷ, Quận 10", district: "quan10", partner: "Lẩu Bò Thảo Cầm Viên", discount: "30K", price: 200000, partnerTier: "growth", estimatedAOV: 200000, commissionRate: 0.07, baseFee: 12000, visibilityLevel: "normal", category: "mid", target: "group", bookings: 452, img: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=800&q=80", icon: "fa-utensils", itinerary: [{time:"18:00",activity:"Ăn vặt đường phố",location:"Hồ Thị Kỷ"},{time:"19:30",activity:"Lẩu bò nhúng dấm",location:"Quận 10"}] },
    { id: 14, title: "Patin Vui Nhộn", desc: "Trượt patin sân băng & Ăn kem", address: "Patin Hoàng Đạo Thúy, Quận 10", district: "quan10", partner: "Mixue Vietnam", discount: "15%", price: 150000, partnerTier: "basic", estimatedAOV: 150000, commissionRate: 0.05, baseFee: 8000, visibilityLevel: "normal", category: "low", target: "both", bookings: 13}]