// Helper functions
const getFallbackImage = (title) => {
    const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="600" height="400" viewBox="0 0 600 400"><rect width="100%" height="100%" fill="#171717"/><text x="50%" y="50%" dominant-baseline="middle" text-anchor="middle" font-family="sans-serif" font-size="24" font-weight="bold" fill="#f43f5e">${title}</text></svg>`;
    return `data:image/svg+xml;charset=utf-8,${encodeURIComponent(svg)}`;
};

const formatMoney = (amount) => new Intl.NumberFormat('vi-VN', { style: 'currency', currency: 'VND' }).format(amount);
const generateGoogleMapsLink = (loc) => `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(`${loc} TP.HCM`)}`;

// Demo combo data. B2B finance now uses partnerPackage only; CPS rate/platform fee live in app.js.
const localComboImages = {
    1: "./acoustic.jpg",
    3: "./boardgame.jpg",
    4: "./TangMayLandMark.jpg",
    5: "./pinicsongao.jpg",
    6: "./HoangHonSup.jpg",
    9: "./giosongSG.jpg",
    10: "./workshopnantuong.jpg",
    11: "./bancung.jpg",
    14: "./patinvuinhon.jpg"
};

const combos = [
    { id: 1, title: "Acoustic Chill", desc: "Nghe nhạc Acoustic & Dạo phố đi bộ", address: "Phố đi bộ Nguyễn Huệ, Quận 1", district: "quan1", partner: "Oromia Coffee", discount: "15%", price: 150000, partnerPackage: "Basic", category: "low", target: "couple", bookings: 125, img: "./acoustic.jpg", icon: "fa-guitar", itinerary: [{ time: "19:00", activity: "Nghe nhạc sống", location: "Oromia Coffee" }, { time: "21:00", activity: "Dạo mát", location: "Phố đi bộ" }, { time: "22:00", activity: "Ăn vặt", location: "Chung cư 42" }] },
    { id: 2, title: "Phim Đêm & Vỉa Hè", desc: "Xem phim rạp & Ăn vặt bánh tráng", address: "CGV Sư Vạn Hạnh, Quận 10", district: "quan10", partner: "CGV Cinemas", discount: "20%", price: 250000, partnerPackage: "Premium", category: "mid", target: "both", bookings: 89, img: "https://images.unsplash.com/photo-1536440136628-849c177e76a1?auto=format&fit=crop&w=800&q=80", icon: "fa-film", itinerary: [{ time: "20:00", activity: "Xem phim bom tấn", location: "CGV Vạn Hạnh Mall" }, { time: "22:30", activity: "Ăn bánh tráng nướng", location: "Hồ Thị Kỷ" }] },
    { id: 3, title: "Đấu Trí Boardgame", desc: "Chơi Boardgame & Uống trà sữa", address: "Cashflow Cafe, Quận 10", district: "quan10", partner: "Cashflow Boardgame", discount: "10%", price: 150000, partnerPackage: "Basic", category: "low", target: "group", bookings: 142, img: "./boardgame.jpg", icon: "fa-chess-knight", itinerary: [{ time: "18:30", activity: "Ăn tối", location: "Mì Ý Double B" }, { time: "19:30", activity: "Ma Sói, Uno", location: "Cashflow Cafe" }] },
    { id: 4, title: "Tầng Mây Landmark", desc: "Trượt băng & Ăn lẩu Haidilao", address: "Landmark 81, Bình Thạnh", district: "binhthanh", partner: "Haidilao Hotpot", discount: "50K", price: 800000, partnerPackage: "Premium", category: "high", target: "couple", bookings: 315, img: "./TangMayLandMark.jpg", icon: "fa-building", itinerary: [{ time: "17:00", activity: "Trượt băng", location: "Vincom Ice Rink" }, { time: "19:30", activity: "Ăn lẩu múa mì", location: "Haidilao Tầng 3" }] },
    { id: 5, title: "Picnic Sống Ảo", desc: "Dã ngoại Thảo Cầm Viên", address: "Thảo Cầm Viên, Quận 1", district: "quan1", partner: "Phúc Long Coffee", discount: "15%", price: 120000, partnerPackage: "Basic", category: "low", target: "group", bookings: 67, img: "./pinicsongao.jpg", icon: "fa-tree", itinerary: [{ time: "08:30", activity: "Mua cafe", location: "Phúc Long Lê Duẩn" }, { time: "09:00", activity: "Trải thảm Picnic", location: "Thảo Cầm Viên" }, { time: "11:30", activity: "Ăn trưa", location: "Dưới bóng cây" }] },
    { id: 6, title: "Hoàng Hôn SUP", desc: "Chèo SUP & Tiệc nướng BBQ", address: "Bến SUP Thanh Đa, Bình Thạnh", district: "binhthanh", partner: "Saigon SUP Club", discount: "20%", price: 750000, partnerPackage: "Premium", category: "high", target: "group", bookings: 278, img: "./HoangHonSup.jpg", icon: "fa-water", itinerary: [{ time: "16:00", activity: "Nhận SUP", location: "Saigon SUP Club" }, { time: "16:30", activity: "Chèo SUP ngắm hoàng hôn", location: "Bán đảo Thanh Đa" }, { time: "18:30", activity: "Tiệc nướng BBQ", location: "Khu vực BBQ" }] },
    { id: 7, title: "Làm Gốm Nghệ Thuật", desc: "Workshop làm gốm đôi & Cafe", address: "Haru Craft Studio, Quận 1", district: "quan1", partner: "Haru Craft", discount: "10%", price: 450000, partnerPackage: "Premium", category: "high", target: "couple", bookings: 134, img: "https://images.unsplash.com/photo-1610701596007-11502861dcfa?auto=format&fit=crop&w=800&q=80", icon: "fa-hands", itinerary: [{ time: "14:00", activity: "Làm gốm", location: "Haru Craft Studio" }, { time: "17:00", activity: "Uống nước, tâm sự", location: "Mockingbird Cafe" }] },
    { id: 8, title: "Bảo Tàng Cổ Điển", desc: "Bảo tàng Mỹ thuật & Chụp ảnh retro", address: "Bảo tàng Mỹ thuật, Quận 1", district: "quan1", partner: "Cơm Tấm Mộc", discount: "15%", price: 100000, partnerPackage: "Basic", category: "low", target: "both", bookings: 112, img: "https://images.unsplash.com/photo-1582555172866-f73bb12a2ab3?auto=format&fit=crop&w=800&q=80", icon: "fa-palette", itinerary: [{ time: "09:00", activity: "Tham quan kiến trúc", location: "Bảo tàng Mỹ thuật" }, { time: "11:30", activity: "Ăn trưa cơm tấm", location: "Cơm Tấm Mộc" }] },
    { id: 9, title: "Gió Sông Sài Gòn", desc: "Waterbus ngắm hoàng hôn & Ăn tối", address: "Bến Bạch Đằng, Quận 1", district: "quan1", partner: "Saigon Waterbus", discount: "10%", price: 300000, partnerPackage: "Growth", category: "mid", target: "both", bookings: 189, img: "./giosongSG.jpg", icon: "fa-ship", itinerary: [{ time: "16:30", activity: "Lên tàu Waterbus", location: "Bến Bạch Đằng" }, { time: "18:30", activity: "Ăn tối ven sông", location: "Khu ẩm thực Bến Bạch Đằng" }] },
    { id: 10, title: "Workshop Nặn Tượng", desc: "Tô tượng, nặn đất sét xả stress", address: "Họa Sĩ Cà Phê, Bình Thạnh", district: "binhthanh", partner: "Họa Sĩ Cà Phê", discount: "20%", price: 180000, partnerPackage: "Premium", category: "low", target: "group", bookings: 145, img: "./workshopnantuong.jpg", icon: "fa-face-smile", itinerary: [{ time: "15:00", activity: "Tô tượng/đất sét", location: "Họa Sĩ Cà Phê" }, { time: "18:00", activity: "Ăn Bún bò Huế", location: "Ngã tư Hàng Xanh" }] },
    { id: 11, title: "Thiện Xạ Bắn Cung", desc: "Câu lạc bộ bắn cung & Ăn gà rán", address: "NVH Thanh Niên, Quận 1", district: "quan1", partner: "Don Chicken", discount: "15%", price: 350000, partnerPackage: "Growth", category: "mid", target: "group", bookings: 167, img: "./bancung.jpg", icon: "fa-bullseye", itinerary: [{ time: "17:00", activity: "Bắn cung", location: "NVH Thanh Niên" }, { time: "19:30", activity: "Phạt người thua", location: "Don Chicken" }] },
    { id: 12, title: "Nightlife Chill", desc: "Pub Acoustic nhẹ nhàng & Cocktails", address: "Carmen Bar, Quận 1", district: "quan1", partner: "Carmen Bar", discount: "10%", price: 550000, partnerPackage: "Premium", category: "high", target: "couple", bookings: 210, img: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?auto=format&fit=crop&w=800&q=80", icon: "fa-martini-glass", itinerary: [{ time: "19:30", activity: "Ăn tối món Âu", location: "El Gaucho" }, { time: "21:00", activity: "Cocktail & Nghe nhạc", location: "Carmen Bar" }] },
    { id: 13, title: "Càn Quét Hồ Thị Kỷ", desc: "Ăn sập phố Hồ Thị Kỷ", address: "Phố ẩm thực Hồ Thị Kỷ, Quận 10", district: "quan10", partner: "Lẩu Bò Thảo Cầm Viên", discount: "30K", price: 200000, partnerPackage: "Growth", category: "mid", target: "group", bookings: 452, img: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=800&q=80", icon: "fa-utensils", itinerary: [{ time: "18:00", activity: "Ăn vặt đường phố", location: "Hồ Thị Kỷ" }, { time: "19:30", activity: "Lẩu bò nhúng dấm", location: "Quận 10" }] },
    { id: 14, title: "Patin Vui Nhộn", desc: "Trượt patin sân băng & Ăn kem", address: "Patin Hoàng Đạo Thúy, Quận 10", district: "quan10", partner: "Mixue Vietnam", discount: "15%", price: 150000, partnerPackage: "Basic", category: "low", target: "both", bookings: 13, img: "./patinvuinhon.jpg", icon: "fa-person-skating", itinerary: [{ time: "16:00", activity: "Trượt patin", location: "Patin Hoàng Đạo Thúy" }, { time: "18:00", activity: "Ăn kem", location: "Mixue Vietnam" }] },
    { id: 15, title: "Cafe Sách Yên Tĩnh", desc: "Đọc sách, học bài nhẹ nhàng & uống cà phê", address: "Đường sách Nguyễn Văn Bình, Quận 1", district: "quan1", partner: "Book Street Cafe", discount: "10%", price: 120000, partnerPackage: "Basic", category: "low", target: "both", bookings: 96, img: "https://images.unsplash.com/photo-1519682337058-a94d519337bc?auto=format&fit=crop&w=800&q=80", icon: "fa-book-open", itinerary: [{ time: "15:00", activity: "Dạo đường sách", location: "Đường sách Nguyễn Văn Bình" }, { time: "16:00", activity: "Cafe & đọc sách", location: "Book Street Cafe" }, { time: "17:30", activity: "Chụp ảnh nhẹ", location: "Nhà thờ Đức Bà" }] },
    { id: 16, title: "Dessert Date", desc: "Ăn bánh ngọt, uống trà và đi dạo trung tâm", address: "Takashimaya, Quận 1", district: "quan1", partner: "Dessert Corner", discount: "15%", price: 220000, partnerPackage: "Growth", category: "mid", target: "couple", bookings: 138, img: "https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&w=800&q=80", icon: "fa-cake-candles", itinerary: [{ time: "14:30", activity: "Ăn bánh & uống trà", location: "Dessert Corner" }, { time: "16:00", activity: "Dạo trung tâm thương mại", location: "Takashimaya" }, { time: "17:30", activity: "Chụp ảnh phố đi bộ", location: "Nguyễn Huệ" }] },
    { id: 17, title: "Kèo Karaoke Nhẹ", desc: "Karaoke nhóm bạn & ăn tối bình dân", address: "Karaoke ICOOL, Quận 10", district: "quan10", partner: "ICOOL Karaoke", discount: "20%", price: 300000, partnerPackage: "Growth", category: "mid", target: "group", bookings: 201, img: "https://images.unsplash.com/photo-1516280440614-37939bbacd81?auto=format&fit=crop&w=800&q=80", icon: "fa-microphone", itinerary: [{ time: "18:00", activity: "Ăn tối cùng nhóm", location: "Khu ăn uống Quận 10" }, { time: "19:30", activity: "Karaoke 2 giờ", location: "ICOOL Karaoke" }, { time: "21:30", activity: "Tráng miệng", location: "Trà sữa gần đó" }] },
    { id: 18, title: "Sáng Chủ Nhật Xanh", desc: "Đi công viên, uống nước ép và chụp ảnh", address: "Công viên Gia Định, Phú Nhuận", district: "phunhuan", partner: "Juice Station", discount: "10%", price: 90000, partnerPackage: "Basic", category: "low", target: "both", bookings: 77, img: "https://images.unsplash.com/photo-1519331379826-f10be5486c6f?auto=format&fit=crop&w=800&q=80", icon: "fa-leaf", itinerary: [{ time: "08:00", activity: "Đi bộ công viên", location: "Công viên Gia Định" }, { time: "09:00", activity: "Uống nước ép", location: "Juice Station" }, { time: "10:00", activity: "Chụp ảnh sáng", location: "Khu cây xanh công viên" }] },
    { id: 19, title: "Workshop Vẽ Tranh", desc: "Vẽ tranh thư giãn & cafe cuối tuần", address: "The Craft House, Quận 7", district: "quan7", partner: "The Craft House", discount: "15%", price: 480000, partnerPackage: "Growth", category: "mid", target: "couple", bookings: 164, img: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&w=800&q=80", icon: "fa-paintbrush", itinerary: [{ time: "14:00", activity: "Workshop vẽ tranh", location: "The Craft House" }, { time: "16:30", activity: "Cafe & xem tranh", location: "Quận 7" }, { time: "17:30", activity: "Dạo Phú Mỹ Hưng", location: "Khu Hồ Bán Nguyệt" }] }
];
